### ISSUE TITLE
Skinning Trouble

### ISSUE THREAD

**Issue by DeCarabas** [bqqbarbhg/ufbx#26]
Thank you so much for this library; it's exactly what I was looking for when it comes to an FBX reading library!

I'm having a bit of trouble with evaluating skins. In particular, I have one model that this library just doesn't seem to make sense of.

I'm using the "overhaul" version of the code, from commit 8237c4fb.

When I load the model without skinning the geometry comes out just fine...

<img width="1430" alt="working" src="https://user-images.githubusercontent.com/9754/133956852-3213b3c5-bc8f-44af-9d19-fff044c398de.png">

...but when I tell ufbx to evaluate skinning and start using `skinned_position` and `skinned_normal` everything goes wrong...

<img width="1430" alt="busted" src="https://user-images.githubusercontent.com/9754/133956938-321527ab-9e70-4ded-9904-4c56a4b48536.png">

FWIW Unity and open3mod both render this FBX just fine, but Godot has the same trouble as I do.

Any advice? I've attached the FBX and Textures.

[repro.zip](https://github.com/bqqbarbhg/ufbx/files/7193606/repro.zip)

**Comment by bqqbarbhg** [comment]
Thanks a lot for the clean issue and repro case, I'll take a look!

**Comment by bqqbarbhg** [comment]
Hopefully fixed in 95d3062, please report back if you can try it at some point!

It at least seems to work in a viewer example I'm working on:

![image](https://user-images.githubusercontent.com/3875461/134050965-8086d695-ec04-44fb-91d8-874054145e9f.png)

Also for interactive purposes you might not want to compute the skinning with `skinned_position` as it's not too well optimized, but it's nice to use as a test/reference to see that things are working fine. If you want to look into implementing GPU skinning there's `ufbx_skin_deformer.vertices` that contains a per-vertex list of `ufbx_skin_weight` structs containing a cluster (bone) index and a weight. These are sorted by descending weight so you can grab say the first 4 weights per vertex (make sure to re-normalize the weights to 1!) and use that with a GPU skinning implementation. I'll hopefully get to making an example of how to use ufbx in a more interactive manner.

**Comment by DeCarabas** [comment]
Thanks! 

Yeah, I was using `skinned_position` as a way of trying to debug my own skinning logic, and when `skinned_position` gave me the same results as my own code I decided I needed help. :)

I'm giving it a try now-- I suspect there are some other things about the transforms in the scene that I'm not fully understanding, but I think it isn't related to the skinning meshes.

**Comment by bqqbarbhg** [comment]
Yea at least the skinned mesh in repro.zip contained *Geometric Transformations*, which is a 3ds Max-specific feature that allows you to transform the meshes in addition to the actual node hierarchy (meaning the geometric transform does not inherit to children). ufbx does not (currently) support baking this transform to vertices so if you use node transform hierarchies make sure to apply the `ufbx_node.geometry_to_node` to the mesh data (or use `ufbx_node.geometry_to_world` instead of `ufbx_node.node_to_world` if you're using that).

**Comment by DeCarabas** [comment]
Ah, nevermind, I found my missing transformations. (I was mistakenly ignoring some nodes in the tree.)

Thanks again for all your help! It's such a fantastic library!

**Comment by bqqbarbhg** [comment]
Thanks for the kind words! I'll add a reminder to explain the transformation hierarchy more in depth in the coming documentation anyway since FBX makes it pretty complicated (well what ufbx presents is still somewhat sane, you wouldn't believe how terrible it's internally :D)

**Comment by DeCarabas** [comment]
As somebody who has written their own incomplete FBX loader at least twice, I understand. It makes me appreciate ufbx all the more. :)
