### ISSUE TITLE
How do I get animations for a particular node?

### ISSUE THREAD

**Issue by grigoryoskin** [bqqbarbhg/ufbx#29]
Alternatively, how to I get a node that animation (ufbx_anim_prop ?) targets?

**Comment by bqqbarbhg** [comment]
The low-level API around the animated curves is really lacking at the moment, sorry for that! In pre-`overhaul` (I hope I get it merged soon, but you might want to consider using it as it has better API and documentation) there is no notion of generic FBX element and so the situation is pretty terrible, but you can use something like:

```c
ufbx_node *get_anim_prop_node(ufbx_scene *scene, ufbx_anim_prop *prop)
{
	switch (prop->target) {
	case UFBX_ANIM_MODEL: return &scene->models.data[prop->index].node;
	case UFBX_ANIM_MESH: return &scene->meshes.data[prop->index].node;
	case UFBX_ANIM_LIGHT: return &scene->lights.data[prop->index].node;
	case UFBX_ANIM_BONE: return &scene->bones.data[prop->index].node;
	default: return NULL;
	}
}
```

However I would recommend against not using the animation curves directly unless you really need them but rather by using one of the high level APIs provided by ufbx as they take care of a lot of the annoying details (Euler angles, rotation order, pre/post rotations, pivots, animation layers, curve interpolation modes, etc).

You can get the evaluated transform at a time for a node using:

```c
typedef struct ufbx_transform {
	ufbx_vec3 translation;
	ufbx_vec4 rotation; // < This is a quaternion, sorry! (fixed as `ufbx_quat` in overhaul)
	ufbx_vec3 scale;
} ufbx_transform;

ufbx_transform ufbx_evaluate_transform(const ufbx_scene *scene, const ufbx_node *node, const ufbx_anim_stack *stack, double time);
```

One approach is to resample the animation using this and then if the resulting data is too large you can try to fit some curves to the data or (what I do) use something like [ACL](https://github.com/nfrechette/acl) to compress it.

There is also an API for evaluating the _whole_ scene that can be handy sometimes. It returns a new `ufbx_scene` where every property is evalauted at a specific time:

```c
ufbx_scene *ufbx_evaluate_scene(const ufbx_scene *scene, const ufbx_evaluate_opts *opts, double time);
// Free with ufbx_free_scene()
```

**Comment by grigoryoskin** [comment]
Thank you for the answer! I'm using it with an engine that already has animation logic, so I'm just trying to extract curves and map them to our engines curves and let it do evaluation itself. Although maybe I could sample transforms over time and use a series of transforms as "curves"...
If I choose to sample transforms with `ufbx_evaluate_transform`, will it work differently in `overhaul`? Should I check it out now or is it ok to use current master?

**Comment by bqqbarbhg** [comment]
The `ufbx_evaluate_transform()` function works pretty much identically in `overhaul`, the only difference is that it takes an `ufbx_anim` as the animation descriptor instead of an `ufbx_anim_stack`. You can pass in either `scene->anim` for the default animation in the file or use `anim_stack->anim` for a specific stack. It also allows for more control over animation evaluation (custom combination of animation layers/weights, property overrides) by specifying a custom `ufbx_anim` structure.

But yea with FBX you either have to deal with Euler angle curves (and all the transform complexity if you want generic FBX support) or resample the animation. In `overhaul` each `ufbx_anim_prop` has a pointer to a generic `ufbx_element` "base class". Each element has a `ufbx_element_type type;` (eg. `UFBX_ELEMENT_NODE`) and can be casted to the matching concrete type.

In general I'd recommend using `overhaul` as it will soon replace the `master` branch when I get all the documentation and examples in check. The data model there is closer to what it is in FBX so instead of having an `ufbx_mesh` which is also a node you'd have separate `ufbx_node` that contains a `ufbx_mesh`. This enables instancing multiple meshes and generally cleans up the whole library a ton. The nodes and their "attributes" are bidirectionally linked via eg. `ufbx_node.mesh` and `ufbx_mesh.instances` being a list of nodes that use the mesh.

**Comment by grigoryoskin** [comment]
Thank you for the advice, I'll try it out!
