### ISSUE TITLE
Problems with 3dsmax FBX

### ISSUE THREAD

**Issue by Novum** [bqqbarbhg/ufbx#41]
I'm trying to read the new Sponza scene from Intel:
https://www.intel.com/content/www/us/en/newsroom/opinion/intel-graphics-step-up-research.html

The issue I'm encountering is that the normal textures in the FBX are kind of weird. There is a link to a texture node that just defines some 3dsmax parameters
```
	Texture: 1690443457600, "Texture::stone_trims_01_Normal", "" {
		Type: "TextureVideoClip"
		Version: 202
		TextureName: "Texture::stone_trims_01_Normal"
		Properties70:  {
			P: "3dsMax", "Compound", "", ""
			P: "3dsMax|ClassIDa", "int", "Integer", "",2121471519
			P: "3dsMax|ClassIDb", "int", "Integer", "",-1235266194
			P: "3dsMax|SuperClassID", "int", "Integer", "",3088
			P: "3dsMax|ai_bump2d Parameters/Connections", "Compound", "", ""
			P: "3dsMax|ai_bump2d Parameters/Connections|bump_map", "Float", "", "A",0
			P: "3dsMax|ai_bump2d Parameters/Connections|bump_map.connected", "Bool", "", "A",1
			P: "3dsMax|ai_bump2d Parameters/Connections|bump_map.shader", "Reference", "", "A"
			P: "3dsMax|ai_bump2d Parameters/Connections|bump_height", "Float", "", "A",1
			P: "3dsMax|ai_bump2d Parameters/Connections|bump_height.connected", "Bool", "", "A",1
			P: "3dsMax|ai_bump2d Parameters/Connections|bump_height.shader", "Reference", "", "A"
			P: "3dsMax|ai_bump2d Parameters/Connections|normal", "Vector", "", "A",0,0,0
			P: "3dsMax|ai_bump2d Parameters/Connections|normal.connected", "Bool", "", "A",1
			P: "3dsMax|ai_bump2d Parameters/Connections|normal.shader", "Reference", "", "A"
			P: "3dsMax|ai_bump2d Results", "Compound", "", ""
		}
		Media: ""
		FileName: ""
		RelativeFilename: ""
		ModelUVTranslation: 0,0
		ModelUVScaling: 1,1
		Texture_Alpha_Source: "None"
		Cropping: 0,0,0,0
	}
```
This is connected to _another_ texture node like this:
```
	;Texture::stone_trims_01_Normal, Texture::stone_trims_01_Normal
	C: "OP",1690443452320,1690443457600, "3dsMax|ai_bump2d Parameters/Connections|bump_map.shader"
```
which is the regular one:
```
	Texture: 1690443452320, "Texture::stone_trims_01_Normal", "" {
		Type: "TextureVideoClip"
		Version: 202
		TextureName: "Texture::stone_trims_01_Normal"
		Properties70:  {
			P: "UVSet", "KString", "", "", "UVChannel_1"
			P: "UseMaterial", "bool", "", "",1
		}
		Media: "Video::stone_trims_01_Normal"
		FileName: "textures/stone_trims_01_Normal.png"
		RelativeFilename: "textures/stone_trims_01_Normal.png"
		ModelUVTranslation: 0,0
		ModelUVScaling: 1,1
		Texture_Alpha_Source: "None"
		Cropping: 0,0,0,0
	}
```

Not quite sure what ufbx should do? Traverse the entire connections when fetching textures?

With empty file names like for the weird texture node it might also make sense to set `UFBX_TEXTURE_PROCEDURAL` instead of `UFBX_TEXTURE_FILE`

**Comment by bqqbarbhg** [comment]
Oh wow nice catch, that's is definitely far from a "standard" FBX way of representing that. It's always difficult to decide where to draw a line for how much "application specific" behavior ufbx should handle. If that specific 3ds Max material model is common then it seems like something that should be included, at least the `3dsMax|Parameters|bump_map` layer still seems sane.

I wouldn't want to blindly traverse through textures at least without a feature flag in `ufbx_load_opts`. One thing to consider could be to make traversing the connections easier for users as currently it is possible but not very intuitive. Properties could have a flag indicating if they have a connected element. The best would be to have a `ufbx_element *element;` in each `ufbx_prop` but this is such a rare feature that I'm not sure if it's worth the hit in size (actually the more I think about it the more I feel like it _might_ be reasonable, as ufbx optimizes API over performance in most cases).

I added an experimental `ufbx_find_prop_element()` that returns the element connected to a property so the normal map could be fetched using (requires `strong-types` branch):

```c
ufbx_material *material = (ufbx_material*)ufbx_find_element(scene, UFBX_ELEMENT_MATERIAL, "stone_trims_01");
// ...
ufbx_texture *meta_texture = ufbx_find_prop_texture(material, "3dsMax|Parameters|bump_map");
ufbx_texture *real_texture = ufbx_as_texture(ufbx_find_prop_element(&meta_texture->element,
    "3dsMax|ai_bump2d Parameters/Connections|bump_map.shader"));
```

I'll need to poke around and see if I can repro this material representation in 3ds Max as I don't like implementing features that I don't really understand. That said I don't mind `ufbx_material_pbr_maps` being somewhat hacky and approximate as it kind of has to be, it does some really nasty trickery with assumptions about Blender exporter behavior for instance.

About `ufbx_texture_type` of the weird property-only-texture it's really hard to say as logically it does represent some kind of procedural value (though not really as that's almost a serialized shader graph node??) but I also don't want to stray too far off from the actual FBX file. I'm still waiting to find a real .fbx file that contains a procedural texture so I could figure out how they should be implemented.

Pre-post-edit: As I was writing this I was thinking that `ai_bump2d` sounds familiar and happened to remember that the `ai` prefix is associated with the Arnold renderer. So looking at https://docs.arnoldrenderer.com/display/A5AFMUG/Bump2d it looks like 3ds Max serializes shader graphs as dummy textures. Absolutely bonkers, need to consider if there's a sane way to expose this behavior, since now for finding a "normal map" you'd have to eyeball a *shader graph* and try to find the most relevant texture. Maybe material maps should just have a list of "associated textures" found recursively.

Anyways thanks for the cursed information, need to mull over what would be the design for this :D

**Comment by Novum** [comment]
No surprise that 3dsmax does something absolutely bonkers. Thanks for investigating! I agree that maybe just giving the user the option to traverse this madness themselves if they have to support abominations like this might be the right call.

**Comment by bqqbarbhg** [comment]
I _think_ I have arrived at a reasonable design:

- Expose the cursed shader textures in a generic way to the user
- No-op / identity (such as component mapping / `ai_bump2d`) shader textures are skipped by default in material texture pointers, there's `shader_texture` to get the real root texture.
- Every `ufbx_texture` has a list of "file textures" that represent it, these are collected recursively from shader graphs and actual FBX built-in layered textures.

This gives us a situation where:

```c
// Here we can trust that `tex` is a faithful approximation of the actual texture,
// if it's a complex shader or a layered texture it will be either UFBX_TEXTURE_LAYERED or UFBX_TEXTURE_SHADER
ufbx_texture *tex = material->pbr.base_color.texture;

// However we can get a less strict approximation of the texture by using
assert(tex->file_textures.count > 0);
ufbx_texture *approx = tex->file_textures.data[0];

// Or if we're feeling extra fancy:
ufbx_texture *better_approx = user_heuristic(tex->file_textures);
```

File textures will always have a single element in `ufbx_texture.file_textures` so doing `texture->file_textures[0]` _always_\* results in a valid file texture, either direct or indirect.

\* Unless there is no file textures to be (recursively) reached.
